/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_instruments_get"];
        put?: never;
        /** Create Instrument */
        post: operations["create_instrument_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument */
        get: operations["get_instrument_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_accounts__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}/instruments/{instrument_id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_accounts__account_id__instruments__instrument_id__position_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit */
        post: operations["deposit_transactions_deposit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Demo Portfolio */
        post: operations["seed_demo_portfolio_demo_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw */
        post: operations["withdraw_transactions_withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Portfolio */
        get: operations["query_portfolio_portfolio_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResponse */
        AccountResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Institution */
            institution: string;
            account_type: components["schemas"]["AccountType"];
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "brokerage" | "ira" | "crypto_exchange" | "cash";
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "equity" | "etf" | "crypto" | "cash";
        /** CreateAccountRequest */
        CreateAccountRequest: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Institution */
            institution: string;
            account_type: components["schemas"]["AccountType"];
        };
        /** CreateInstrumentRequest */
        CreateInstrumentRequest: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            asset_class: components["schemas"]["AssetClass"];
        };
        /** CreateTransactionRequest */
        CreateTransactionRequest: {
            /** Account Id */
            account_id: string;
            /** Instrument Id */
            instrument_id: string;
            type: components["schemas"]["TransactionType"];
            /** Quantity */
            quantity: number | string;
            /** Price */
            price: number | string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** DemoSeedResponse */
        DemoSeedResponse: {
            /** Seeded */
            seeded: boolean;
        };
        /** DepositRequest */
        DepositRequest: {
            /** Account Id */
            account_id: string;
            /** Amount */
            amount: number | string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * Granularity
         * @enum {string}
         */
        Granularity: "daily" | "weekly" | "monthly" | "yearly";
        /**
         * GroupBy
         * @enum {string}
         */
        GroupBy: "none" | "instrument" | "account";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentResponse */
        InstrumentResponse: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            asset_class: components["schemas"]["AssetClass"];
        };
        /**
         * Metric
         * @enum {string}
         */
        Metric: "equity" | "share_count" | "cost_basis" | "cash_balance" | "unrealized_gain" | "realized_gain" | "market_price";
        /**
         * Mode
         * @enum {string}
         */
        Mode: "point_in_time" | "cumulative" | "delta_per_period";
        /** PositionResponse */
        PositionResponse: {
            /** Account Id */
            account_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Share Count */
            share_count: string;
            /** Cost Basis */
            cost_basis: string;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Group */
            group: string;
            /** Points */
            points: components["schemas"]["TimeSeriesPointResponse"][];
        };
        /** TimeSeriesPointResponse */
        TimeSeriesPointResponse: {
            /**
             * Timestamp
             * Format: date
             */
            timestamp: string;
            /** Value */
            value: string;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Id */
            id: string;
            /** Account Id */
            account_id: string;
            /** Instrument Id */
            instrument_id: string;
            type: components["schemas"]["TransactionType"];
            /** Quantity */
            quantity: string;
            /** Price */
            price: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Trade Id */
            trade_id: string | null;
        };
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "buy" | "sell";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WithdrawalRequest */
        WithdrawalRequest: {
            /** Account Id */
            account_id: string;
            /** Amount */
            amount: number | string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_instruments_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentResponse"][];
                };
            };
        };
    };
    create_instrument_instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstrumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_accounts_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    create_account_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_accounts__account_id__instruments__instrument_id__position_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deposit_transactions_deposit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_demo_portfolio_demo_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSeedResponse"];
                };
            };
        };
    };
    withdraw_transactions_withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_portfolio_portfolio_query_get: {
        parameters: {
            query: {
                metric: components["schemas"]["Metric"];
                start: string;
                end: string;
                granularity: components["schemas"]["Granularity"];
                mode: components["schemas"]["Mode"];
                instruments?: string[] | null;
                accounts?: string[] | null;
                group_by?: components["schemas"]["GroupBy"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
